# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:RNyPppHbDNE+h6CZ+hxZ5RxohyMQorSkSdbAgjPSd0ZPA8SLXnnPViQCn+YNgXr3m/ciOd/u99Lgb2PdklfOmNrGpoJ4r+mYhJkH+rWOybA6C35UqWTSfStqPwjNySHvUz1VmMwx+vfDg5WiJX1N+nZ/LPTjOC6kWAhfiqqBgfnxVlEi5lg3SdvfZ3RXBQXQagESrPptqBMm1Ev1KgiBTf/AvcyG1syVOKcZF/YPnOhAH5pD,iv:l5pOdEMvKseI5qWABRxbENKXqBTYgym+s0cHUhEUUQw=,tag:83BPwzGrlPdk6lY45ujBug==,type:str]
sops:
  age:
    - recipient: age1unftnr5e5hd034m8qkpru6cerlfyxguupkxwc8p9z2gnx37m2y4q6h6pqj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRXNhL0NxWUc4Yi8wb2pw
        SGVsTUxxdGVjL1lFOGtJTzZvYUdRZkNST0F3CmIzU1psbnRhR2Y4OUVlQml2L1F5
        VDJPVEhMTkdzcXZkTlV0UFcvQzlBQkEKLS0tIFA3eEY0YzZSMGt1Q3VLRjRWN0E0
        ckdEWUlEQnVpc3BzN2NYOFZTSDBEZncKTY7y8QzSYC1GzyKPY9A6/4/upVyx3D7h
        8l/EX77LqUUspPuL2FLIgd3vOHqH4M3qBaMpnYREOhSQTbRk03PgFA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-03T17:28:13Z"
  mac: ENC[AES256_GCM,data:fzCgyqccJWNM2bAjeeLzq1Z3fr4H8T5B5MNjezld1GWrY0+g1bPVmYRlw38MQUzyjtWQk7Dvnrz6syZZ7PZWqkkIq9oBbXQJE4hPQormW0HFZ5A2gGxrY8o4QBAtRZDjlomE/DNWox1pBStcnHgil2pZ7kHUgXap4PZ5ackGgk8=,iv:Qix51Ms7o2iiGF2bt1Qc4cK8xnX5H5HBiyk/PRBmNHU=,tag:51+xHKVgeftM0/xuACpuaw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
