# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:/LfvYnJ0aFnsE1wiFRBspSC9EcEhPerpjGo7noYL5O6Q//XX5QjHHw==,iv:PbqQ4v6G2Hf6e19xNEe0AVTJcWdrpQfBv1goPoI3ygg=,tag:pDhxfvF7qlFE6/l2uiuv3g==,type:str]
sops:
  age:
    - recipient: age1unftnr5e5hd034m8qkpru6cerlfyxguupkxwc8p9z2gnx37m2y4q6h6pqj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzOHZTTG9IZ3FTQ0tTN2hk
        K2EwYWZqZVRrMHo3eFBxTXl1K3lyclpFMjFZCmIzd1QwNXg1MUVoYXV6cXF4NVh0
        TDVWbFc3VWdUK05KNHg2aWNyTWg2ZlkKLS0tIGxxNnh0ZGtHOTN2QnZYb1Vsbmp2
        SXhBTDV6YnYwYUxyR0JCTkpvYnExbVEKn3SVXT2RmUe8qYCjxxTtn2Ye7zPRUQAG
        XFfqTAGmWT1q/0IuDZddMsfQDinEeSs/P2yNEZ9Ix64ucpknTWMxJw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-03T17:28:13Z"
  mac: ENC[AES256_GCM,data:yKkoCqJ/Y6Xd1ZGB1g5wn1SihxhWTECzGmjdwduEUzH9yGHr8sXO4MExrTOfWN/KyZi0pQvON9xsXmeLqwDtM39lTWnCka+BhNlbkkLqe5M/OFGqXOMTAcIT8LoQaJ9iKFuFIDnCGsEDVm07Uflqa6yyzLRO80XAzw+GZAOarNE=,iv:fWufg/C3YeuK6HmjQiHkZ48Z74QrI7jtsJdcCC5t51Q=,tag:PRQvbv8w75w32Y4IScBWqw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
