apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:rTS8gm4CyQqZP+EQGA==,iv:G8pewNPo369f5GiPo1vJv2gFPTN9g0yO0URnEyOzgz8=,tag:Z2tAMUOv1S9IjRcA6Iq0LQ==,type:str]
sops:
  age:
    - recipient: age1unftnr5e5hd034m8qkpru6cerlfyxguupkxwc8p9z2gnx37m2y4q6h6pqj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQlA2NktFMjNscDVOZmo4
        b1k0VU1XcVlqdDlhM3Y1NEdnNHJ2em9weWx3CjdyZGdhTWpaNkRzK0RvampjVEl6
        Y1VHYUxqcGFOeFFLcm1LSlRFLzJVWVkKLS0tIG84YzVYdStpV0hqUWRzNnpETnNs
        QVg2cHZ6N0h4QmNIV0FvcldmS3ZKbVkKb5aU+6AOMEDLS89565Di10Y/zsrf/DBp
        OCA8X5V1NC7lT91tPw82a9rwGCpbI04KJnH8oQGy2R+Wn962qaRsUw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-03T18:36:26Z"
  mac: ENC[AES256_GCM,data:reo9mOGo995WbHUjKe0GmzHIqwW3gD1kULsiwy8od5FE3LuNwxEKhLKoH8k4AyUUCcPKW7ZoCgDa95rSW7kg49x2bUr/6QaJKdD75D+gPwHOlNIIh1BS+K1Iq21FjopCkM4o3V1A123FpXhgXKn+DkYdETanjkhAy5yBJiiyDfc=,iv:6UFuS7zeaT7sUM16Qcn2FyAjdZAfuJzd+YmyphJ0iR4=,tag:5ZXPwFp/Jc3cRkcZhuuBQA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
